# Generated by Django 6.1.1 on 2026-09-07 17:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_seed_doctors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'заявка на приём', 'verbose_name_plural': 'Заявки на приём'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['full_name'], 'verbose_name': 'врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=120, verbose_name='имя и фамилия пациента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.doctor', verbose_name='врач'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{7,15}$', 'Введите от 7 до 15 цифр; в начале допустим знак +.')], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='requested_at',
            field=models.DateTimeField(db_index=True, verbose_name='желаемые дата и время'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=12, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(70)], verbose_name='стаж, лет'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='имя и фамилия'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='специальность'),
        ),
    ]
