# Generated by Django 6.1.1 on 2026-09-27 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_userprofile_appointment_client_appointmentslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='appointmentslot',
            options={'ordering': ['starts_at'], 'verbose_name': 'время записи', 'verbose_name_plural': 'Время записи'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['full_name'], 'verbose_name': 'мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=120, verbose_name='имя и фамилия клиента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.doctor', verbose_name='мастер'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='направление'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Пациент'), ('doctor', 'Мастер'), ('manager', 'Менеджер')], default='client', max_length=10),
        ),
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000, verbose_name='сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clinic.appointment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сообщение клиента',
                'verbose_name_plural': 'Чаты клиентов',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('category', models.CharField(choices=[('nails', 'Маникюр и педикюр'), ('hair', 'Волосы'), ('brows', 'Брови и ресницы'), ('makeup', 'Макияж'), ('care', 'Уход')], max_length=10, verbose_name='категория')),
                ('description', models.CharField(max_length=240, verbose_name='описание')),
                ('price', models.PositiveIntegerField(verbose_name='цена, ₽')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(60)], verbose_name='длительность, минут')),
                ('is_active', models.BooleanField(default=True, verbose_name='доступна для записи')),
                ('specialists', models.ManyToManyField(related_name='services', to='clinic.doctor', verbose_name='мастера')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.salonservice', verbose_name='услуга'),
        ),
    ]
