# Generated by Django 6.1.1 on 2026-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_seed_beauty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('doctor', 'Мастер'), ('manager', 'Менеджер')], default='client', max_length=10),
        ),
    ]
